# Generated by Django 5.2.4 on 2025-08-12 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_rate',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
    ]
